### ISSUE TITLE
Cannot input binary to convert to string

### ISSUE THREAD

**Issue by Ethan-Yocom** [Choketa/MorseCode#1]
While I can convert an inputted string into binary, I cannot convert a binary input into a string

**Comment by Choketa** [comment]
Dear Rockyers,

Upon reading your issue, my heart shattered to pieces, yet, I had to reassemble it through pain and struggle, the pain and struggle being the process of fixing the issue. After lots of trial and error, I succeeded in my mission, and my heart is complete.
I hope this fix will bring more light to your day.

Yours truly,
Nuke5721226.

**Comment by Ethan-Yocom** [comment]
Thank you so much! I am very pleased
